[package]
name = "test-task"
version = "0.1.0"
authors = ["Georgy Moshkin <louielouie314@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
num_cpus = "1.13"

[features]
fun = []
